### ISSUE TITLE
AttributeError: 'Seq2Seq' object has no attribute 'getword'

### ISSUE THREAD

**Issue by tennnx** [LHRYANG/CRL_EGPG#3]
Hi author, **AttributeError: 'Seq2Seq' object has no attribute 'getword'** this error occurred when I run ''evaluate.py'. I have checked that the class Seq2Seq has no function named 'getword'. Could you please help to tell why is this error and how to solve it? Thanks!

**Comment by tennnx** [comment]
hhh, I have just solved this problem. Thanks~

**Comment by xing-ye** [comment]
> hhh, I have just solved this problem. Thanks~

Hello, I also encountered this problem, can you tell me how you solved it, thank you

**Comment by hi-im-buggy** [comment]
@tennnx could you please explain how you solved the issue? Thanks

edit: I was able to solve it myself. You have to use the `getword` function in `modules/utils`, by changing the import at the top to `from modules.utils import loadpkl, getword`, and changing the call to just `getword` instead of `seq2seq2.getword`
